
export const ADD_USER = "ADD_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAIL = "ADD_USER_FAIL"

export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const GET_ALL_USER = "GET_ALL_USER"
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL"

export const ACTIVE_DEACTIVE_USER = "ACTIVE_DEACTIVE_USER"
export const ACTIVE_DEACTIVE_USER_SUCCESS = "ACTIVE_DEACTIVE_USER_SUCCESS"
export const ACTIVE_DEACTIVE_USER_FAIL = "ACTIVE_DEACTIVE_USER_FAIL"

