
export const GENERATE_QR_CODE = "GENERATE_QR_CODE"
export const GENERATE_QR_CODE_SUCCESS = "GENERATE_QR_CODE_SUCCESS"
export const GENERATE_QR_CODE_FAIL = "GENERATE_QR_CODE_FAIL"

export const VERIFY_OTP = "VERIFY_OTP"
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL"